### PR TITLE
Get comments for pull requests

### LINKED ISSUE #10: Get pull request review comments, not just issues comments
Currently, we [just get **issues** comments](https://github.com/joyent/git-apply-pr/blob/master/apply-pr.js#L107) when looking for a LGTM string. However, GitHub's API has different types of comments:
- _Issues_ comments: these are the comments found in issues, but also in pull requests except for those attached to the unified diff, because pull requests are considered as issues.
- _Pull request_ comments: these are the comments attached to a pull request' unified diff.
- _Commit_ comments.

Getting only issues comments prevents us from finding a `LGTM` written in a comment attached to a PR's diff. https://github.com/joyent/sdc-vmapi/pull/8 is a good example of such a PR:

```
➜  sdc-vmapi git:(master) node ~/dev/git-apply-pr/apply-pr.js joyent/sdc-vmapi#8 | git am -
this PR has not been LGTMd
➜  sdc-vmapi git:(master)
```

The fix should be simple, as replacing `github.issues.getComments` by `github.pullRequests.getComments` fixed this specific example. I should be able to put together a PR for that soon.

### PR DESCRIPTION
**Pull request by riyadhalnur**
Fixes #10

### CODE REVIEW

**Comment by robertkowalski** [comment]
+1 thank you mate!

**Comment by robertkowalski** [comment]
merged as 52c69c7cf2639e32c7b5f243b26bb3f3c59c4181

**Comment by riyadhalnur** [comment]
@robertkowalski cheers mate :smiley:

**Comment by robertkowalski** [comment]
published as 1.2.2 :)

**Comment by misterdjules** [comment]
@robertkowalski @riyadhalnur Did you test this change with a PR that has only issues comments? In #10 I wrote:

> The fix should be simple, as replacing github.issues.getComments by github.pullRequests.getComments fixed this specific example. I should be able to put together a PR for that soon.

which meant that replacing `github.issues.getComments` by `github.pullRequests.getComments` fixed _that specific example_, but was not necessarily a fix for all possible cases. In general, I would expect that we'd need to process both issues comments _and_ pull requests comments.

**Comment by robertkowalski** [comment]
doh!

looks like we need some tests soon

**Comment by robertkowalski** [comment]
sorry!

**Comment by misterdjules** [comment]
@robertkowalski No worries, as you said we need tests :)

**Comment by robertkowalski** [comment]
it is pretty late here, i don't have time today any more, maybe tomorrow!

**Comment by misterdjules** [comment]
@robertkowalski Of course, I didn't mean that this needed to be done today. Thank you for all your help!

**Comment by riyadhalnur** [comment]
@misterdjules @robertkowalski sorry about that. tests would be nice

**Pull request closed without merging**
