### PR TITLE
changed github.issues,getComments to github.pullRequests.getComments

### PR DESCRIPTION
**Pull request by milose**
This is a fix for #10

### CODE REVIEW

**Comment by robertkowalski** [comment]
awesome, thank you so much! :heart_eyes: 

@misterdjules can you confirm that it fixes the issue you reported?

**Comment by riyadhalnur** [comment]
@milose @robertkowalski already opened a PR to fix #10

**Comment by robertkowalski** [comment]
ah sorry @riyadhalnur! I just merged your PR :)

**Comment by robertkowalski** [comment]
superseded by #10,  thanks @milose and sorry that you had no luck here!

**Pull request closed without merging**
